export let products = [
  {
    id: "1",
    name: "Beef Short Rib",
    price: 18.99,
    type: "meat",
    imgUrl: "../images/items/meat/beef-short-rib.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "2",
    name: "Beef Tenderloin Roast",
    price: 24.99,
    type: "meat",
    imgUrl: "../images/items/meat/beef-tenderloin-roast.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "3",
    name: "Wagyu Beef",
    price: 22.99,
    type: "meat",
    imgUrl: "../images/items/meat/wagyu-beef.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "4",
    name: "Chicken Breast",
    price: 4.49,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-breast.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "7",
    name: "Chicken Drumstick",
    price: 2.99,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-drumstick.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "8",
    name: "Chicken Thighs",
    price: 3.49,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-thighs.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "9",
    name: "Whole Roasting Chicken",
    price: 1.99,
    type: "meat",
    imgUrl: "../images/items/meat/whole-chicken.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "10",
    name: "Goat Meat",
    price: 28.99,
    type: "meat",
    imgUrl: "../images/items/meat/goat-meat.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "11",
    name: "Ground Beef",
    price: 5.99,
    type: "meat",
    imgUrl: "../images/items/meat/ground-beef.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "12",
    name: "Pork Meat",
    price: 2,
    type: "meat",
    imgUrl: "../images/items/meat/pork-meat.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "13",
    name: "Smoked Ham Steak",
    price: 6.99,
    type: "meat",
    imgUrl: "../images/items/meat/ham-steak.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "14",
    name: "Lamb Loin Chops",
    price: 6.99,
    type: "meat",
    imgUrl: "../images/items/meat/lamb-loin.jpg",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "15",
    name: "Turkey Tenderloins",
    price: 6.49,
    type: "meat",
    imgUrl: "../images/items/meat/turkey-tenderloin.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "16",
    name: "Rabbit Meat",
    price: 11.99,
    type: "meat",
    imgUrl: "../images/items/meat/whole-rabbit-meat.png",
    rating: 3,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
  },
  {
    id: "17",
    name: "Boneless Bangus",
    price: 7.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/boneless-bangus.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "18",
    name: "Cod Fillets",
    price: 9.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/cod-fillet.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "19",
    name: "Tilapia Fillets",
    price: 7.59,
    type: "seafood",
    imgUrl: "../images/items/seafoods/tilapia fillet.png",
    rating: 3,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "20",
    name: "Trout Fillets",
    price: 16,
    type: "seafood",
    imgUrl: "../images/items/seafoods/trout-fillet.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "21",
    name: "Jumbo King Crab Legs",
    price: 39.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/jumbo-alaskan-king-crab-legs.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "22",
    name: "Lobster Tails",
    price: 29.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/lobster-tail.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "23",
    name: "Peeled Shrimps",
    price: 5,
    type: "seafood",
    imgUrl: "../images/items/seafoods/peeled-shrimp.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "24",
    name: "Jumbo Shrimps",
    price: 18.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/shrimp.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "25",
    name: "Octopus",
    price: 9.49,
    type: "seafood",
    imgUrl: "../images/items/seafoods/octopus.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "26",
    name: "Scallops",
    price: 19.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/scallops.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "27",
    name: "Sea Bass Fillets",
    price: 17.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/sea-bass-fillet.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "28",
    name: "Squid",
    price: 6.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/squid.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "29",
    name: "Swordfish Steak",
    price: 18.49,
    type: "seafood",
    imgUrl: "../images/items/seafoods/swordfish-steak.png",
    rating: 3,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "30",
    name: "Tuna Steak",
    price: 16.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/tuna-steak.png",
    rating: 3,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
  },
  {
    id: "31",
    name: "Bell Pepper (Assorted)",
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/bell-pepper.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "32",
    name: "Broccoli",
    price: 1.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/broccoli.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "33",
    name: "Brussels Sprouts",
    price: 4.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/brussels-sprouts.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "34",
    name: "Butternut Squash",
    price: 2.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/butternut-squash.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "35",
    name: "Cabbage",
    price: 1.69,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cabbage.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "36",
    name: "Squash",
    price: 1.29,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/squash.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "37",
    name: "Carrots",
    price: 1.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/carrots.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "38",
    name: "Celery",
    price: 2.79,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/celery.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "39",
    name: "Chilli Pepper",
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/chilli.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "40",
    name: "Cucumbers",
    price: 2.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cucumbers.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "41",
    name: "Cauliflowers",
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cauliflower.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "42",
    name: "Eggplant",
    price: 3.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/eggplant.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "43",
    name: "Lettuce",
    price: 3.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/fresh-lettuce.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "44",
    name: "Garlic",
    price: 5.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/garlic.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "45",
    name: "Kale",
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/kale.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "46",
    name: "Mushrooms",
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/mushroom.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "47",
    name: "Ladies Fingers",
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/okra.png",
    rating: 4,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "48",
    name: "Onions",
    price: 1.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/onions.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "49",
    name: "Green Peas",
    price: 0.54,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/peas.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "50",
    name: "Sweet Potatoes",
    price: 2.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/sweet-potato.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
  {
    id: "51",
    name: "Tomatoes",
    price: 2.69,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/tomatoes.png",
    rating: 5,
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
  },
];
