export let productItems = [
  {
    id: 1,
    name: "Beef Short Rib",
    basePrice: 18.99,
    price: 18.99,
    type: "meat",
    imgUrl: "../images/items/meat/beef-short-rib.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 2,
    name: "Beef Tenderloin Roast",
    basePrice: 24.99,
    price: 24.99,
    type: "meat",
    imgUrl: "../images/items/meat/beef-tenderloin-roast.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 3,
    name: "Wagyu Beef",
    basePrice: 22.99,
    price: 22.99,
    type: "meat",
    imgUrl: "../images/items/meat/wagyu-beef.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 4,
    name: "Chicken Breast",
    basePrice: 4.49,
    price: 4.49,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-breast.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 5,
    name: "Chicken Drumstick",
    basePrice: 2.99,
    price: 2.99,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-drumstick.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 6,
    name: "Chicken Thighs",
    basePrice: 3.49,
    price: 3.49,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-thighs.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 7,
    name: "Whole Roasting Chicken",
    basePrice: 1.99,
    price: 1.99,
    type: "meat",
    imgUrl: "../images/items/meat/whole-chicken.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 8,
    name: "Goat Meat",
    basePrice: 28.99,
    price: 28.99,
    type: "meat",
    imgUrl: "../images/items/meat/goat-meat.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 9,
    name: "Ground Beef",
    basePrice: 5.99,
    price: 5.99,
    type: "meat",
    imgUrl: "../images/items/meat/ground-beef.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 10,
    name: "Pork Meat",
    basePrice: 2,
    price: 2,
    type: "meat",
    imgUrl: "../images/items/meat/pork-meat.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 11,
    name: "Smoked Ham Steak",
    basePrice: 6.99,
    price: 6.99,
    type: "meat",
    imgUrl: "../images/items/meat/ham-steak.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 12,
    name: "Lamb Loin Chops",
    basePrice: 6.99,
    price: 6.99,
    type: "meat",
    imgUrl: "../images/items/meat/lamb-loin.jpg",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 13,
    name: "Turkey Tenderloins",
    basePrice: 6.49,
    price: 6.49,
    type: "meat",
    imgUrl: "../images/items/meat/turkey-tenderloin.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 14,
    name: "Rabbit Meat",
    basePrice: 11.99,
    price: 11.99,
    type: "meat",
    imgUrl: "../images/items/meat/whole-rabbit-meat.png",
    order: 1,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: true,
  },
  {
    id: 15,
    name: "Boneless Bangus",
    basePrice: 7.99,
    price: 7.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/boneless-bangus.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 16,
    name: "Cod Fillets",
    basePrice: 9.99,
    price: 9.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/cod-fillet.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 17,
    name: "Tilapia Fillets",
    basePrice: 7.59,
    price: 7.59,
    type: "seafood",
    imgUrl: "../images/items/seafoods/tilapia fillet.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 18,
    name: "Trout Fillets",
    basePrice: 16,
    price: 16,
    type: "seafood",
    imgUrl: "../images/items/seafoods/trout-fillet.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 19,
    name: "Jumbo King Crab Legs",
    basePrice: 39.99,
    price: 39.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/jumbo-alaskan-king-crab-legs.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 20,
    name: "Lobster Tails",
    basePrice: 29.99,
    price: 29.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/lobster-tail.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 21,
    name: "Peeled Shrimps",
    basePrice: 5,
    price: 5,
    type: "seafood",
    imgUrl: "../images/items/seafoods/peeled-shrimp.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 22,
    name: "Jumbo Shrimps",
    basePrice: 18.99,
    price: 18.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/shrimp.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 23,
    name: "Octopus",
    basePrice: 9.49,
    price: 9.49,
    type: "seafood",
    imgUrl: "../images/items/seafoods/octopus.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 24,
    name: "Scallops",
    basePrice: 19.99,
    price: 19.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/scallops.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 25,
    name: "Sea Bass Fillets",
    basePrice: 17.99,
    price: 17.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/sea-bass-fillet.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 26,
    name: "Squid",
    basePrice: 6.99,
    price: 6.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/squid.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 27,
    name: "Swordfish Steak",
    basePrice: 18.49,
    price: 18.49,
    type: "seafood",
    imgUrl: "../images/items/seafoods/swordfish-steak.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 28,
    name: "Tuna Steak",
    basePrice: 16.99,
    price: 16.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/tuna-steak.png",
    order: 1,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: true,
  },
  {
    id: 29,
    name: "Bell Pepper (Assorted)",
    basePrice: 3.99,
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/bell-pepper.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 30,
    name: "Broccoli",
    basePrice: 1.99,
    price: 1.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/broccoli.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 31,
    name: "Brussels Sprouts",
    basePrice: 4.99,
    price: 4.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/brussels-sprouts.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 32,
    name: "Butternut Squash",
    basePrice: 2.99,
    price: 2.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/butternut-squash.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 33,
    name: "Cabbage",
    basePrice: 1.69,
    price: 1.69,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cabbage.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 34,
    name: "Squash",
    basePrice: 1.29,
    price: 1.29,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/squash.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 35,
    name: "Carrots",
    basePrice: 1.49,
    price: 1.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/carrots.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 36,
    name: "Celery",
    basePrice: 2.79,
    price: 2.79,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/celery.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 37,
    name: "Chilli Pepper",
    basePrice: 4.49,
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/chilli.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 38,
    name: "Cucumbers",
    basePrice: 2.49,
    price: 2.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cucumbers.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 39,
    name: "Cauliflowers",
    basePrice: 3.99,
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cauliflower.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 40,
    name: "Eggplant",
    basePrice: 3.49,
    price: 3.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/eggplant.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 41,
    name: "Lettuce",
    basePrice: 3.49,
    price: 3.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/fresh-lettuce.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 42,
    name: "Garlic",
    basePrice: 5.99,
    price: 5.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/garlic.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 43,
    name: "Kale",
    basePrice: 4.49,
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/kale.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 44,
    name: "Mushrooms",
    basePrice: 4.49,
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/mushroom.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 45,
    name: "Ladies Fingers",
    basePrice: 3.99,
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/okra.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 46,
    name: "Onions",
    basePrice: 1.99,
    price: 1.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/onions.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 47,
    name: "Green Peas",
    basePrice: 0.54,
    price: 0.54,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/peas.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 48,
    name: "Sweet Potatoes",
    basePrice: 2.49,
    price: 2.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/sweet-potato.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 49,
    name: "Tomatoes",
    basePrice: 2.69,
    price: 2.69,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/tomatoes.png",
    order: 1,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: true,
  },
  {
    id: 50,
    name: "Apple",
    basePrice: 1.99,
    price: 1.99,
    type: "fruit",
    imgUrl: "../images/items/fruits/fresh-apple.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 51,
    name: "Mango",
    basePrice: 1.49,
    price: 1.49,
    type: "fruit",
    imgUrl: "../images/items/fruits/fresh-mango.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 52,
    name: "Pineapple",
    basePrice: 3.99,
    price: 3.99,
    type: "fruit",
    imgUrl: "../images/items/fruits/fresh-pineapple.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 53,
    name: "Oranges",
    basePrice: 1.29,
    price: 1.29,
    type: "fruit",
    imgUrl: "../images/items/fruits/oranges.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 54,
    name: "Avocado",
    basePrice: 1,
    price: 1,
    type: "fruit",
    imgUrl: "../images/items/fruits/avocado.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 55,
    name: "Banana",
    basePrice: 0.59,
    price: 0.59,
    type: "fruit",
    imgUrl: "../images/items/fruits/banana.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 56,
    name: "Grapes",
    basePrice: 2.99,
    price: 2.99,
    type: "fruit",
    imgUrl: "../images/items/fruits/grapes.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 57,
    name: "Strawberries",
    basePrice: 3.39,
    price: 3.39,
    type: "fruit",
    imgUrl: "../images/items/fruits/strawberry.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 58,
    name: "Blueberries",
    basePrice: 5,
    price: 5,
    type: "fruit",
    imgUrl: "../images/items/fruits/blueberry.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 59,
    name: "Blackberries",
    basePrice: 5.29,
    price: 5.29,
    type: "fruit",
    imgUrl: "../images/items/fruits/blackberry.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 60,
    name: "Raspberries",
    basePrice: 1.54,
    price: 1.54,
    type: "fruit",
    imgUrl: "../images/items/fruits/raspberry.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 61,
    name: "Grape Fruit",
    basePrice: 1.39,
    price: 1.39,
    type: "fruit",
    imgUrl: "../images/items/fruits/grapefruit.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 62,
    name: "Kiwi",
    basePrice: 0.65,
    price: 0.65,
    type: "fruit",
    imgUrl: "../images/items/fruits/kiwi.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 63,
    name: "Guava",
    basePrice: 1.29,
    price: 1.29,
    type: "fruit",
    imgUrl: "../images/items/fruits/guava.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 64,
    name: "Lemons",
    basePrice: 0.79,
    price: 0.79,
    type: "fruit",
    imgUrl: "../images/items/fruits/lemon.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 65,
    name: "Limes",
    basePrice: 0.69,
    price: 0.69,
    type: "fruit",
    imgUrl: "../images/items/fruits/lime.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 66,
    name: "Papaya",
    basePrice: 1.89,
    price: 1.89,
    type: "fruit",
    imgUrl: "../images/items/fruits/papaya.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 67,
    name: "Pomegranate",
    basePrice: 2.39,
    price: 2.39,
    type: "fruit",
    imgUrl: "../images/items/fruits/pomegranate.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: false,
  },
  {
    id: 68,
    name: "Starfruit",
    basePrice: 2.89,
    price: 2.89,
    type: "fruit",
    imgUrl: "../images/items/fruits/startfruit.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
  {
    id: 69,
    name: "Mixed Fruit Salad",
    basePrice: 5.99,
    price: 5.99,
    type: "fruit",
    imgUrl: "../images/items/fruits/mixed-fruit-salad.png",
    order: 1,
    themeColor: "#EE3841",
    icon: "../images/product-icon-category/fruits-icon.png",
    isPerPound: true,
  },
];
