export let productItems = [
  {
    id: 1,
    name: "Beef Short Rib",
    price: 18.99,
    type: "meat",
    imgUrl: "../images/items/meat/beef-short-rib.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 2,
    name: "Beef Tenderloin Roast",
    price: 24.99,
    type: "meat",
    imgUrl: "../images/items/meat/beef-tenderloin-roast.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 3,
    name: "Wagyu Beef",
    price: 22.99,
    type: "meat",
    imgUrl: "../images/items/meat/wagyu-beef.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 4,
    name: "Chicken Breast",
    price: 4.49,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-breast.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 5,
    name: "Chicken Drumstick",
    price: 2.99,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-drumstick.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 6,
    name: "Chicken Thighs",
    price: 3.49,
    type: "meat",
    imgUrl: "../images/items/meat/chicken-thighs.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 7,
    name: "Whole Roasting Chicken",
    price: 1.99,
    type: "meat",
    imgUrl: "../images/items/meat/whole-chicken.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 8,
    name: "Goat Meat",
    price: 28.99,
    type: "meat",
    imgUrl: "../images/items/meat/goat-meat.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 9,
    name: "Ground Beef",
    price: 5.99,
    type: "meat",
    imgUrl: "../images/items/meat/ground-beef.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 10,
    name: "Pork Meat",
    price: 2,
    type: "meat",
    imgUrl: "../images/items/meat/pork-meat.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 11,
    name: "Smoked Ham Steak",
    price: 6.99,
    type: "meat",
    imgUrl: "../images/items/meat/ham-steak.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 12,
    name: "Lamb Loin Chops",
    price: 6.99,
    type: "meat",
    imgUrl: "../images/items/meat/lamb-loin.jpg",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 13,
    name: "Turkey Tenderloins",
    price: 6.49,
    type: "meat",
    imgUrl: "../images/items/meat/turkey-tenderloin.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 14,
    name: "Rabbit Meat",
    price: 11.99,
    type: "meat",
    imgUrl: "../images/items/meat/whole-rabbit-meat.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#CA0000",
    icon: "../images/product-icon-category/meat-icon.png",
    isPerPound: false,
  },
  {
    id: 15,
    name: "Boneless Bangus",
    price: 7.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/boneless-bangus.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 16,
    name: "Cod Fillets",
    price: 9.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/cod-fillet.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 17,
    name: "Tilapia Fillets",
    price: 7.59,
    type: "seafood",
    imgUrl: "../images/items/seafoods/tilapia fillet.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 18,
    name: "Trout Fillets",
    price: 16,
    type: "seafood",
    imgUrl: "../images/items/seafoods/trout-fillet.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 19,
    name: "Jumbo King Crab Legs",
    price: 39.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/jumbo-alaskan-king-crab-legs.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 20,
    name: "Lobster Tails",
    price: 29.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/lobster-tail.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 21,
    name: "Peeled Shrimps",
    price: 5,
    type: "seafood",
    imgUrl: "../images/items/seafoods/peeled-shrimp.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 22,
    name: "Jumbo Shrimps",
    price: 18.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/shrimp.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 23,
    name: "Octopus",
    price: 9.49,
    type: "seafood",
    imgUrl: "../images/items/seafoods/octopus.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 24,
    name: "Scallops",
    price: 19.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/scallops.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 25,
    name: "Sea Bass Fillets",
    price: 17.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/sea-bass-fillet.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 26,
    name: "Squid",
    price: 6.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/squid.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 27,
    name: "Swordfish Steak",
    price: 18.49,
    type: "seafood",
    imgUrl: "../images/items/seafoods/swordfish-steak.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 28,
    name: "Tuna Steak",
    price: 16.99,
    type: "seafood",
    imgUrl: "../images/items/seafoods/tuna-steak.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#1B7080",
    icon: "../images/product-icon-category/seafood-icon.png",
    isPerPound: false,
  },
  {
    id: 29,
    name: "Bell Pepper (Assorted)",
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/bell-pepper.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 30,
    name: "Broccoli",
    price: 1.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/broccoli.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 31,
    name: "Brussels Sprouts",
    price: 4.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/brussels-sprouts.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 32,
    name: "Butternut Squash",
    price: 2.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/butternut-squash.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 33,
    name: "Cabbage",
    price: 1.69,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cabbage.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 34,
    name: "Squash",
    price: 1.29,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/squash.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 35,
    name: "Carrots",
    price: 1.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/carrots.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 36,
    name: "Celery",
    price: 2.79,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/celery.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 37,
    name: "Chilli Pepper",
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/chilli.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 38,
    name: "Cucumbers",
    price: 2.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cucumbers.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 39,
    name: "Cauliflowers",
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/cauliflower.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 40,
    name: "Eggplant",
    price: 3.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/eggplant.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 41,
    name: "Lettuce",
    price: 3.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/fresh-lettuce.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 42,
    name: "Garlic",
    price: 5.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/garlic.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 43,
    name: "Kale",
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/kale.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 44,
    name: "Mushrooms",
    price: 4.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/mushroom.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 45,
    name: "Ladies Fingers",
    price: 3.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/okra.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 46,
    name: "Onions",
    price: 1.99,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/onions.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 47,
    name: "Green Peas",
    price: 0.54,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/peas.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 48,
    name: "Sweet Potatoes",
    price: 2.49,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/sweet-potato.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
  {
    id: 49,
    name: "Tomatoes",
    price: 2.69,
    type: "vegetable",
    imgUrl: "../images/items/vegetables/tomatoes.png",
    order: 0,
    isAddedToCart: false,
    orderDate: null,
    themeColor: "#91AB24",
    icon: "../images/product-icon-category/vegetables-icon.png",
    isPerPound: false,
  },
];
